### ISSUE TITLE
Update repo for maintainability

### ISSUE THREAD

**Issue by willingc** [pyOpenSci/pyosMeta#78]
Evolving code bases often need some "cleaning" to help the repo be understandable and maintainable by future contributors. This issue will track the series of steps to be taken while cleaning.

## Phase 1
Update repo root for maintainability:

- [x] Simplify README for readability
    - Add badges
    - Create sections that would be expected
    - Update title to reflect that the repo will be renamed in the future to the `pyosmeta` to match the package name
- [x] Create a `CONTRIBUTING.md` file and move usage instructions from existing README to it
- [x] Create a `CODE_OR_CONDUCT.md` file and add text to refer to the pyOpenSci CoC page
- [x] Create a `CHANGELOG.md` file which will contain a badge to PyPI for first iteration
- [x] Create a `LICENSE` file at the repo root for MIT license with content from `src/LICENSE.txt` and drop the `.txt` suffix
- [x] Remove `src/LICENSE.txt` and `src/README.md`

## Phase 2
- [x] Review the development tools config (flake8, recommit, gitignore, etc.)

## Phase 3
- [ ] Correct any errors surfaced by running code inspectors

## Phase 4
- [ ] Add module/file docstrings
- [ ] Review function, class, and public method docstrings and edit as needed

## Phase 5
Begin code enhancements such as adding a CLI that allows running: `pyosmeta <task> <commandline>`

**Comment by willingc** [comment]
@lwasser We'll be pairing on this with you doing the bulk of the PR reviews.

**Comment by lwasser** [comment]
@all-contributors please add @willingc for code, review

**Comment by lwasser** [comment]
yes please @willingc 

excited to work on this with you! i also just added two other issues that will improve the package's infrastructure. i'll do a better job of updating the changelog as well from now on. because i've been the only person working on this, I know it's missing a lot of core package elements.  I appreciate getting to work with you on this!

**Comment by willingc** [comment]
Closing this since I think we will cover Phase 3, 4, and 5 during incremental refactor of the repo.
